import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../../public/assets/css/plugins/swiper.min.css";
import "../../public/assets/css/style.css";
import "../../public/assets/css/custom.css";
import "bootstrap-icons/font/bootstrap-icons.min.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import CartOverlay from "@/components/CartOverlay";
import AppProvider from "./AppProvider";
import { getCart } from "@/lib/models/Cart";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();
  const cart = await getCart();

  return (
    <SessionProvider session={session}>
      <AppProvider shopCart={cart}>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}

            <CartOverlay />
          </body>

          <script src="/assets/js/plugins/jquery.min.js" defer async></script>
          <script
            src="/assets/js/plugins/bootstrap.bundle.min.js"
            async
            defer
          ></script>
          <script
            src="/assets/js/plugins/bootstrap-slider.min.js"
            async
            defer
          ></script>
          <script src="/assets/js/plugins/swiper.min.js" defer async></script>
          <script src="/assets/js/plugins/countdown.js" defer async></script>
          <script src="/assets/js/theme.js" defer async></script>
        </html>
      </AppProvider>
    </SessionProvider>
  );
}

export default RootLayout;
